name: digging_yuhak
description: 디깅유학 - 유학 정보 매거진 및 커뮤니티 앱

publish_to: 'none'

version: 2.1.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  carousel_slider: ^5.1.1
  url_launcher: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  # Authentication and state management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  # Form validation and UI
  email_validator: ^2.1.17
  fluttertoast: ^8.2.4
  # Date and time utilities
  timeago: ^3.6.0
  # Image picker for user content
  image_picker: ^1.0.4
  # Local storage
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/